// Extract operator-authored turns from Claude Code transcripts.
import { createReadStream, readdirSync, writeFileSync, mkdirSync, renameSync } from "node:fs";
import { createInterface } from "node:readline";
import { createHash } from "node:crypto";
import { join, basename, dirname } from "node:path";

// Machine-authored transcripts: swarm leaves, subagents, agent-* files.
const SKIP_DIR = /swarm-runs|[\\/]subagents[\\/]/i;
const SKIP_FILE = /^agent-/i;

// Blocks injected into a human turn by the harness, not typed by the human.
const STRIP = [
  /<system-reminder>[\s\S]*?<\/system-reminder>/g,
  /<command-name>[\s\S]*?<\/command-name>/g,
  /<command-message>[\s\S]*?<\/command-message>/g,
  /<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g,
  /<local-command-caveat>[\s\S]*?<\/local-command-caveat>/g,
  /<ide_[a-z_]+>[\s\S]*?<\/ide_[a-z_]+>/g,
  /<task-notification>[\s\S]*?<\/task-notification>/g,
];
const REJECT = [
  /^Cache keepalive tick/,
  /^\[Request interrupted/,
  /^<task-notification/,
  /^This session is being continued from a previous conversation/,
  /^Caveat: The messages below were generated by the user while running local commands/,
  /^<bash-(input|stdout|stderr)>/,
  /^\[Image #\d+\]$/,
];

export function* walkTranscripts(dir) {
  let entries;
  try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) { if (!SKIP_DIR.test(p)) yield* walkTranscripts(p); }
    else if (e.name.endsWith(".jsonl") && !SKIP_FILE.test(e.name) && !SKIP_DIR.test(p)) yield p;
  }
}

function textOf(content) {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return null;
  if (content.some(b => b && b.type === "tool_result")) return null;
  return content.filter(b => b && b.type === "text").map(b => b.text).join("\n");
}

export function cleanTurn(text) {
  let t = text;
  const a = t.match(/<command-args>([\s\S]*?)<\/command-args>/);
  if (a) t = a[1];
  for (const re of STRIP) t = t.replace(re, "");
  return t.trim();
}

// Pasted-in content vs typed prose. Tagged, not dropped.
export function classifyTurn(t) {
  const lines = t.split("\n");
  const indented = lines.filter(l => /^ {2,}\S/.test(l)).length;
  if (/^[●⏺]/.test(t) || /\n[●⏺] /.test(t)) return "pasted-claude";
  if (lines.length >= 4 && indented / lines.length > 0.3) return "pasted-claude";
  if (/^\[(scout|\d{4}\/\d\d)/.test(t) || /^(Traceback|Error:|PS [A-Z]:)/.test(t)) return "pasted-log";
  if (/^@tool|^```|^\s*[{[]/.test(t) || /^(import|export|function|class|def|const|var)\b/.test(t)) return "pasted-code";
  return "typed";
}

// Script-agnostic word count: Intl.Segmenter handles languages without spaces (CJK, Thai).
const SEG = typeof Intl !== "undefined" && Intl.Segmenter ? new Intl.Segmenter(undefined, { granularity: "word" }) : null;
export function wordCount(t) {
  if (!SEG) return t.split(/\s+/).filter(Boolean).length;
  let n = 0;
  for (const s of SEG.segment(t)) if (s.isWordLike) n++;
  return n;
}

// Decide whether a transcript line is a human-authored turn; returns the record or null.
export function humanTurn(o, file) {
  if (!o || o.type !== "user" || o.isSidechain || o.isMeta || o.isCompactSummary) return null;
  const kind = o.origin && o.origin.kind;
  if (kind) { if (kind !== "human" && kind !== "channel") return null; }
  else if (o.entrypoint === "sdk-cli" || o.promptSource === "sdk") return null;
  const raw = textOf(o.message && o.message.content);
  if (raw == null) return null;
  const text = cleanTurn(raw);
  if (!text || REJECT.some(re => re.test(text))) return null;
  return {
    ts: o.timestamp || null, project: basename(dirname(file)), session: o.sessionId || null,
    origin: kind || "legacy", kind: classifyTurn(text), words: wordCount(text), text,
  };
}

export async function mine({ transcriptsDir, outFile }) {
  const seen = new Set();
  const stats = { files: 0, lines: 0, kept: 0, dup: 0, byKind: {}, byProject: {} };
  const out = [];
  for (const file of walkTranscripts(transcriptsDir)) {
    stats.files++;
    const rl = createInterface({ input: createReadStream(file, "utf8"), crlfDelay: Infinity });
    for await (const line of rl) {
      stats.lines++;
      if (!line.includes('"type":"user"')) continue;
      let o; try { o = JSON.parse(line); } catch { continue; }
      const rec = humanTurn(o, file);
      if (!rec) continue;
      const h = createHash("sha1").update(rec.text).digest("hex").slice(0, 16);
      if (seen.has(h)) { stats.dup++; continue; }
      seen.add(h);
      out.push(rec);
      stats.kept++;
      stats.byKind[rec.kind] = (stats.byKind[rec.kind] || 0) + 1;
      stats.byProject[rec.project] = (stats.byProject[rec.project] || 0) + 1;
    }
  }
  out.sort((a, b) => (a.ts || "").localeCompare(b.ts || ""));
  if (outFile) {
    mkdirSync(dirname(outFile), { recursive: true });
    writeFileSync(outFile + ".tmp", out.map(r => JSON.stringify(r)).join("\n") + "\n");
    renameSync(outFile + ".tmp", outFile);
  }
  const words = out.filter(r => r.kind === "typed").map(r => r.words).sort((a, b) => a - b);
  const pct = q => words[Math.floor(q * (words.length - 1))] || 0;
  stats.typedWords = { total: words.reduce((a, b) => a + b, 0), p50: pct(.5), p90: pct(.9), p99: pct(.99) };
  return { turns: out, stats };
}
